from setuptools import setup, find_packages

setup(
    name="license-plate-case",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "fire",
        "certifi>=2024.12.14",
        "charset-normalizer>=3.4.1",
        "contourpy>=1.3.1",
        "cycler>=0.12.1",
        "easyocr>=1.7.2",
        "filelock>=3.17.0",
        "fonttools>=4.55.5",
        "fsspec>=2024.12.0",
        "idna>=3.10",
        "imageio>=2.37.0",
        "imutils>=0.5.4",
        "Jinja2>=3.1.5",
        "kiwisolver>=1.4.8",
        "lap>=0.5.12",
        "lazy_loader>=0.4",
        "MarkupSafe>=3.0.2",
        "matplotlib>=3.10.0",
        "mpmath>=1.3.0",
        "networkx>=3.4.2",
        "ninja>=1.11.1.3",
        "numpy>=2.2.2",
        "opencv-python>=4.11.0.86",
        "opencv-python-headless>=4.11.0.86",
        "packaging>=24.2",
        "pandas>=2.2.3",
        "pillow>=11.1.0",
        "psutil>=6.1.1",
        "py-cpuinfo>=9.0.0",
        "pyclipper>=1.3.0.post6",
        "pyparsing>=3.2.1",
        "python-bidi>=0.6.3",
        "python-dateutil>=2.9.0.post0",
        "pytz>=2024.2",
        "PyYAML>=6.0.2",
        "requests>=2.32.3",
        "scikit-image>=0.25.0",
        "scipy>=1.15.1",
        "seaborn>=0.13.2",
        "shapely>=2.0.6",
        "six>=1.17.0",
        "sympy>=1.13.1",
        "tifffile>=2025.1.10",
        "torch>=2.5.1",
        "torchvision>=0.20.1",
        "tqdm>=4.67.1",
        "triton>=3.1.0",
        "typing_extensions>=4.12.2",
        "tzdata>=2025.1",
        "ultralytics>=8.3.66",
        "ultralytics-thop>=2.0.14",
        "urllib3>=2.3.0",
        "basicsr>=1.4.2",
        "facexlib>=0.3.0",
        "gfpgan>=1.3.8"
    ],
    entry_points={
        'console_scripts': [
            'license-plate-case=license_plate_case.cli:main',
        ],
    },
    author="Gabriel Cunha",
    author_email="gsalomaoc@gmail.com",
    description="A tool for license plate detection and tracking",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/Gcunhaa/case-computer-vision",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.10",
) 